export const ROLES: Record<string, Record<"admin" | "standard", string[]>> = {
  backoffice: {
    admin: [
      "/dashboard",
      "/backoffice/work-queue/list",
      "/backoffice/work-queue/:id/view",
      "/backoffice/action-center/list",
      "/backoffice/action-center/:id/view",
      "/backoffice/host-management/list",
      "/backoffice/host-management/:id/view",
      "/backoffice/host-management/list",
      "/backoffice/action-center/list",
      "/backoffice/action-center/:id/view",
      "/host/vehicle/:id/view",
      "/host/vehicle/:id/edit",
      "/backoffice/receipt",
      "/backoffice/tag-shipping",
      "/backoffice/tag-master-exports",
      "/backoffice/guest-pay",
      "/backoffice/reports/facility-financials",
      "/backoffice/reports/facility-occupancy",
      "/backoffice/reports/denied-tags",
      "/backoffice/reports/city-pass-count",
      "/backoffice/reports/traveler-invoices",
      "/backoffice/reports/system",
      "/backoffice/reports/guest-pay",
      "/backoffice/message-center/list",
      "/backoffice/message-center/new",
      "/backoffice/contract-parking/pool-management",
      "/backoffice/withdraws",
      "/backoffice/call-center",
      "/backoffice/management/document",
      "/backoffice/management/activity",
      "/backoffice/management/device-monitoring",
     
      "/user/list",
      "/user/add",
      "/user/:id/edit",
      "/my-account",
      "/external/invoice/:id",
      "/backoffice/locations",
    ],
    standard: ["/dashboard"],
  },
  host: {
    admin: [
      "/host/vehicle/list",
      "/host/vehicle/add",
      "/host/vehicle/:id/view",
      "/host/vehicle/:id/edit",
      "/host/vehicle/:id/activate",
      "/host/vehicle/:id/activity",
      "/host/vehicle/activate/bulk",
      "/host/product/list",
      "/host/invoice/list",
      "/host/facility/list",
      "/host/chase-car/list",
      "/host/delivery-fee",
      "/host/reserved-space/list",
      "/host/tag-ordering",
      "/host/guest-pay/list",
      "/host/guest-pay/add",
      "/host/fuel-tank/list",
      "/host/fuel-tank/withdraw",
      "/host/referral/list",
      "/host/user/list",
      "/host/user/add",
      "/host/user/:id/edit",
      "/host/qr-management",
      "/host/locations",
      "/my-account",
      "/external/invoice/:id",
    ],
    standard: [
      "/host/vehicle/list",
      "/host/vehicle/add",
      "/host/vehicle/:id/view",
      "/host/vehicle/:id/edit",
      "/host/locations",
      "/my-account",
      "/external/invoice/:id",
    ],
  },
  facility: {
    admin: [
      "/facility/vehicle-search",
      "/facility/reports/financials",
      "/facility/reports/occupancy",
      "/user/list",
      "/user/add",
      "/user/:id/edit",
      "/my-account",
    ],
    standard: [
      "/dashboard",
      "/facility/vehicle-search",
      "/my-account",
      "/external/invoice/:id",
    ],
  },
  pool: {
    admin: ["/pool/contract-parking/pool-management"],
    standard: ["/pool/contract-parking/pool-management"],
  },
  callcenter: {
    admin: ["/callcenter/hub"],
    standard: ["/callcenter/hub"],
  },
};
